// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY2KMo5u-4nA-xH9RCCNReyYhE6vMS5Kk',
    appId: '1:325249949856:web:f9ca296e3ce79c852de9c5',
    messagingSenderId: '325249949856',
    projectId: 'my-notes-9198',
    authDomain: 'my-notes-9198.firebaseapp.com',
    storageBucket: 'my-notes-9198.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmqb8wdQonp7KZcEoVWBvHOopT8Y3Mz3g',
    appId: '1:325249949856:android:bdf78e8a9c4eb38b2de9c5',
    messagingSenderId: '325249949856',
    projectId: 'my-notes-9198',
    storageBucket: 'my-notes-9198.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC31CAXNVgOKkOvesTe_YsO8mvZsGjyoPA',
    appId: '1:325249949856:ios:e08fba32398f9f932de9c5',
    messagingSenderId: '325249949856',
    projectId: 'my-notes-9198',
    storageBucket: 'my-notes-9198.appspot.com',
    iosClientId: '325249949856-umlambn2cdq24m7o2ea53d8isrnas4v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC31CAXNVgOKkOvesTe_YsO8mvZsGjyoPA',
    appId: '1:325249949856:ios:e08fba32398f9f932de9c5',
    messagingSenderId: '325249949856',
    projectId: 'my-notes-9198',
    storageBucket: 'my-notes-9198.appspot.com',
    iosClientId: '325249949856-umlambn2cdq24m7o2ea53d8isrnas4v2.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
